# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
